[project]
name = "bdr-api-tools"
version = "0.0.0"
description = "Scripts for interacting with the Brown Digital Repository API."
readme = ""
requires-python = ">=3.12,<3.13"
dependencies = ["httpx"]

[dependency-groups]
local = []
staging = []
prod = []
